### ISSUE TITLE
Setting sender_id

### ISSUE THREAD

**Issue by gerasimos** [botfront/rasa-webchat#281] opened 2020-08-28 14:26 UTC
Hello,

Is there an easy way to set Rasa `sender_id` when initiating the webchat widget, other than modifying the webchat socketio implementation and the session management? I would like to "login" users that reside on Rasa backend.

Thank you,
Gerasimos

**Comment by MatthieuJnon** [comment] 2020-08-31 13:58
Hi, this is a duplicate of https://github.com/botfront/rasa-webchat/issues/233

**Closed by MatthieuJnon** 2020-08-31 13:58 UTC
